### ISSUE TITLE
V 1.0.0 checklist

### ISSUE THREAD

**Issue by bartelink** [jet/FsCodec#18]
There's no real blocker for a non-RC release, but given the central role the `IEvent` and `IIndexedEvent` interfaces occupy in Equinox, Propulsion and apps based thereon, it really is the last chance to do a breaking change for the foreseeable. This is the complete list of ideas - how many actually get actioned is up for debate
- [x] Consider renaming `IEvent` to something that doesn't clash with / shadow `FSharp.Control.IEvent`
- [x] make `IndexedEventData.new` align with `EventData.Create`
- [x] consider hiding `EventData` record and/or its equality or comparison facilities
- [x] consider having `IUnionEncoder.Encode` accept a `Context` in order that a single Codec instance can contextually enrich events with `correlationId` and `causationId` values

**Comment by bartelink** [comment]
All resolved+merged; release imminent
