### ISSUE TITLE
V3 checklist

### ISSUE THREAD

**Issue by bartelink** [jet/FsCodec#60]
List of breaking changes to consider for next major version:

- [x] Shift all naming to favor STJ-based naming and/or genericity
   - [ ] Make Newtonsoft converters - e.g. `TypeSafeEnumConverter` generic over the DU case in question (probably less important now given autoTypeSafeEnumAsJsonString mode in #71) - skipped for now unless someone values it enough to make it a PR
    - [x] Rename Settings to Options.
- [x] Remove net461 support, target netstandard/net6.0 only (Equinox 4, Propulsion 3 is doing the same)
